---
apiVersion: v1
kind: Namespace
metadata:
  name: evil
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: centos-victim
  name: centos-victim
  namespace: evil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos-victim
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: centos-victim
    spec:
      containers:
      - image: centos:8
        name: centos-victim
        command: ["/bin/sleep", "3650d"]
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: centos-victim-ssh
  namespace: evil
spec:
  type: NodePort
  ports:
  - targetPort: 22
    port: 22
    nodePort: 30022
  selector:
    app: centos-victim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: centos-attacker
  name: centos-attacker
  namespace: evil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos-attacker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: centos-attacker
    spec:
      containers:
      - image: centos:8
        name: centos-attacker
        command: ["/bin/sleep", "3650d"]
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: centos-attacker-ssh
  namespace: evil
spec:
  type: NodePort
  ports:
  - targetPort: 22
    port: 22
    nodePort: 30022
  selector:
    app: centos-attacker
